controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - propeller_FL_link_joint
      - propeller_FR_link_joint
      - propeller_BL_link_joint
      - propeller_BR_link_joint
      