controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drone_thrust_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    camera_360_controller:
      type: position_controllers/JointGroupPositionController

drone_thrust_controller:
  ros__parameters:
    joints:
      - propeller_FL_link_joint
      - propeller_FR_link_joint
      - propeller_BL_link_joint
      - propeller_BR_link_joint
    command_interfaces:
      - velocity
    gains:
      propeller_FL_link_joint: {p: 100.0, i: 0.01, d: 1.0}
      propeller_FR_link_joint: {p: 100.0, i: 0.01, d: 1.0}
      propeller_BL_link_joint: {p: 100.0, i: 0.01, d: 1.0}
      propeller_BR_link_joint: {p: 100.0, i: 0.01, d: 1.0}

camera_360_controller:
  ros__parameters:
    joints:
      - camera_360_link_joint
      - camera_joint_1_link_joint
      - camera_joint_2_link_joint
    command_interfaces:
      - position