controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    # Individual controllers for each propeller
    propeller_fl_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    propeller_fr_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    propeller_bl_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    propeller_br_controller:
      type: velocity_controllers/JointGroupVelocityController

# Front Left Propeller Controller
propeller_fl_controller:
  ros__parameters:
    joints: ['propeller_FL_link_joint']
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
    reference_timeout: 1.0
    velocity_limit: 3000.0

# Front Right Propeller Controller
propeller_fr_controller:
  ros__parameters:
    joints: ['propeller_FR_link_joint']
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
    reference_timeout: 1.0
    velocity_limit: 3000.0

# Back Left Propeller Controller
propeller_bl_controller:
  ros__parameters:
    joints: ['propeller_BL_link_joint']
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
    reference_timeout: 1.0
    velocity_limit: 3000.0

# Back Right Propeller Controller
propeller_br_controller:
  ros__parameters:
    joints: ['propeller_BR_link_joint']
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
    reference_timeout: 1.0
    velocity_limit: 3000.0