#!/bin/sh

# Versión modificada del script de startup para conectar con modelo existente

set +e
. px4-alias.sh

PATH="$PATH:${R}etc/init.d-posix"

# Configurar para usar modelo existente
set VEHICLE_TYPE                none
set LOGGER_ARGS                 ""
set LOGGER_BUF                  1000
set RUN_MINIMAL_SHELL           no
set SYS_AUTOSTART=4001  # Configuración manual

# NO hacer spawn del modelo, usar el existente
if [ "$PX4_SIM_MODEL" = "none" ] || [ -z "$PX4_SIM_MODEL" ]
then
    echo "Using existing Gazebo model, no spawn needed"
    SYS_AUTOSTART=4001
fi

# Cargar parámetros normalmente
set PARAM_FILE parameters.bson
set PARAM_BACKUP_FILE parameters_backup.bson

param select $PARAM_FILE
if [ -f $PARAM_FILE ]; then
    if ! param import
    then
        echo "ERROR [init] param import failed"
        bsondump $PARAM_FILE
        cp $PARAM_FILE param_import_fail.bson
        
        if [ -f $PARAM_BACKUP_FILE ]
        then
            echo "[init] importing from parameter backup"
            bsondump $PARAM_BACKUP_FILE
            param import $PARAM_BACKUP_FILE
            cp $PARAM_BACKUP_FILE $PARAM_FILE
        fi
        param status
    fi
elif [ -f $PARAM_BACKUP_FILE ]; then
    echo "ERROR [init] primary param file $PARAM_FILE unavailable, using backup $PARAM_BACKUP_FILE"
    param import $PARAM_BACKUP_FILE
fi

param select-backup $PARAM_BACKUP_FILE

[ $RUN_MINIMAL_SHELL = yes ] && exit 0

# Configuración de autostart para modelo existente
if param compare SYS_AUTOSTART $SYS_AUTOSTART
then
    set AUTOCNF no
else
    set AUTOCNF yes
    param set SYS_AUTOCONFIG 1
fi

# Configurar parámetros para simulación
param set MAV_SYS_ID $((px4_instance+1))
param set UXRCE_DDS_KEY $((px4_instance+1))

if [ $AUTOCNF = yes ]
then
    param set SYS_AUTOSTART $SYS_AUTOSTART
    
    # Configurar sensores simulados
    param set CAL_ACC0_ID  1310988
    param set CAL_GYRO0_ID 1310988
    param set CAL_ACC1_ID  1310996
    param set CAL_GYRO1_ID 1310996
    param set CAL_ACC2_ID  1311004
    param set CAL_GYRO2_ID 1311004
    
    param set CAL_MAG0_ID 197388
    param set CAL_MAG0_PRIO 50
    param set CAL_MAG1_ID 197644
    param set CAL_MAG1_PRIO 50
    
    param set SENS_BOARD_X_OFF 0.000001
    param set SENS_DPRES_OFF 0.001
fi

# Configuración de parámetros por defecto
param set-default BAT1_N_CELLS 4
param set-default COM_CPU_MAX -1
param set-default COM_RAM_MAX -1
param set-default COM_RC_IN_MODE 1
param set-default EKF2_REQ_GPS_H 0.5
param set-default IMU_GYRO_FFT_EN 1
param set-default MAV_PROTO_VER 2
param set-default MC_AT_EN 1
param set-default SDLOG_MODE 1
param set-default SDLOG_PROFILE 131
param set-default SDLOG_DIRS_MAX 7
param set-default TRIG_INTERFACE 3
param set-default SYS_FAILURE_EN 1
param set-default COM_LOW_BAT_ACT 3

# Inicializar el simulador sin spawn
dataman start

# Conectar con Gazebo existente en lugar de hacer spawn
echo "Connecting to existing Gazebo model..."
# NO ejecutar px4-rc.simulator que hace el spawn

load_mon start

# Continuar con el resto de módulos normalmente
if param compare SIM_BAT_ENABLE 1
then
    battery_simulator start
fi

system_power_simulator start
tone_alarm start
rc_update start
manual_control start
sensors start
commander start

# Estimadores de estado
if param compare -s EKF2_EN 1
then
    ekf2 start &
fi

if param compare -s LPE_EN 1
then
    local_position_estimator start
fi

if param compare -s ATT_EN 1
then
    attitude_estimator_q start
fi

if ! pwm_out_sim start -m sim
then
    tune_control play error
fi

# Configuración específica del vehículo
. ${R}etc/init.d/rc.vehicle_setup

navigator start

# UXRCE-DDS Client
uxrce_dds_ns=""
if [ "$px4_instance" -ne "0" ]
then
    uxrce_dds_ns="-n px4_$px4_instance"
fi

if [ "${PX4_UXRCE_DDS_NS+x}" ]; then
    if [ -n "$PX4_UXRCE_DDS_NS" ]; then
        uxrce_dds_ns="-n $PX4_UXRCE_DDS_NS"
    else
        uxrce_dds_ns=""
    fi
fi

if [ -n "$ROS_DOMAIN_ID" ]
then
    param set UXRCE_DDS_DOM_ID $ROS_DOMAIN_ID
else
    param set UXRCE_DDS_DOM_ID 0
fi

uxrce_dds_port=8888
if [ -n "$PX4_UXRCE_DDS_PORT" ]
then
    uxrce_dds_port="$PX4_UXRCE_DDS_PORT"
fi

uxrce_dds_client start -t udp -h 127.0.0.1 -p $uxrce_dds_port $uxrce_dds_ns

# Módulos adicionales
if param greater -s MNT_MODE_IN -1
then
    gimbal start
fi

if param greater -s TRIG_MODE 0
then
    camera_trigger start
    camera_feedback start
fi

if param compare -s IMU_GYRO_FFT_EN 1
then
    gyro_fft start
fi

if param compare -s IMU_GYRO_CAL_EN 1
then
    gyro_calibration start
fi

if param compare -s PD_GRIPPER_EN 1
then
    payload_deliverer start
fi

if param compare -s ICE_EN 1
then
    internal_combustion_engine_control start
fi

. px4-rc.mavlink

# Logging
if param compare -s EKF2_EN 1
then
    set LOGGER_ARGS "-p ekf2_timestamps"
else
    set LOGGER_ARGS "-p vehicle_attitude"
fi
. ${R}etc/init.d/rc.logging

mavlink boot_complete
replay trystart